name: Test pandoc script

# see https://github.com/actions/setup-python#using-setup-python-with-a-self-hosted-runner
# for artifact handling and SBOM: https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts

on:
  push:
  #pull_request: # Not necessary, as it is already been executed on push
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3"
        cache: 'pip' # caching pip dependencies
    - name: print versions for debugging
      run: python --version ; pip --version ; whoami ; pwd
    - name: Install graphviz & default-jdk
      if: False
      run: |
        sudo apt-get update
        sudo apt-get upgrade --yes
        sudo apt-get install graphviz default-jdk
        sudo apt-get upgrade --yes
    - name: Update pip
      if: False
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools
    - name: Install dependencies
      if: False
      run: |
        python -m pip install -r ./sphinx-config/requirements.txt
    - name: ls -al
      run: |
        ls -al
    - name: run pandoc
      uses: docker://pandoc/core:3.7
      with:
        args: >- # allows you to break string into multiple lines
          --from=./source/jspwiki.lua
          --columns=100
          --list-tables=true
          --extract-media ./transformed
          --write=native
          --output=./transformed/bold_italic.native
          ./tests/bold_italic.wiki
    - name: Archive sphinx public folder
      uses: actions/upload-artifact@v4
      with:
        name: sphinx-public
        path: |
          ./transformed/
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
